name = "INTSMP Server Modpack"
author = "Fahman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4fa24312b35d9cb8b33a8a0876710988f1206372db375d2759c00e37ea7fa55"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
