name = "INTSMP Server Modpack"
author = "Fahman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcb3ee43dd80311ccb35c7da691ea40038ee47b99e1f1d625cb3aeed1aa91f22"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
